### ISSUE TITLE
Examples hangs on chip

### ISSUE THREAD

**Issue by alfoudam** [DaleGia/Nano33BLESensor#2] opened 2020-09-12 11:39 UTC
Hi

Whatever the example code, the chip will hangs.
IE: 
13:35:08.163 -> Temperature, Humidity
13:35:08.163 -> 
 and nothing more

**Comment by DaleGia** [comment] 2020-09-12 17:38
Thanks for reporting @alfoudam. I'll look at this over the next couple of days and report back as to what's going wrong. I did have a working copy of this example, but it is possible I committed a wrong version.

**Comment by DaleGia** [comment] 2020-09-15 14:02
Hi again @alfoudam. I tested the example again and can confirm that it functions as intended. The the data to be outputted a bluetooth device must connect to the Nano 33 BLE Sense first. Once a connection is made, temperature and humidity values will be printed out every 5 seconds.

It is easy enough to strip out all the bluetooth functionality from the code if you do not require it. I'll close this issue for now. Hope this explanation helps.

**Closed as completed by DaleGia** 2020-09-15 14:02 UTC
