### ISSUE TITLE
Error with CircularBuffer

### ISSUE THREAD

**Issue by sabas1080** [DaleGia/Nano33BLESensor#1] opened 2020-09-10 21:16 UTC
Hi @DaleGia 

I have the next error with Arduino Mbed in nano ble

```
In file included from libraries/Nano33BLESensor/src/Nano33BLEMicrophoneRMS.h:34:0,
                 from libraries/Nano33BLESensor/examples/Nano33BLESensorExample_microphoneRMS/Nano33BLESensorExample_microphoneRMS.ino:31:
/libraries/Nano33BLESensor/src/Nano33BLESensorBuffer.h:55:15: error: 'CircularBuffer' in namespace 'mbed' does not name a template type
         mbed::CircularBuffer<T, BUFFER_SIZE> buffer;
               ^~~~~~~~~~~~~~
/Users/xxx/Documents/Arduino/libraries/Nano33BLESensor/src/Nano33BLESensorBuffer.h: In instantiation of 'bool Nano33BLESensorBuffer<T>::pop(T&) [with T = Nano33BLEMicrophoneRMSData]':
/Users/xxxx/Documents/Arduino/libraries/Nano33BLESensor/examples/Nano33BLESensorExample_microphoneRMS/Nano33BLESensorExample_microphoneRMS.ino:133:48:   required from here
/Users/sabas/Documents/Arduino/libraries/Nano33BLESensor/src/Nano33BLESensorBuffer.h:68:18: error: 'class Nano33BLESensorBuffer<Nano33BLEMicrophoneRMSData>' has no member named 'buffer'
     return this->buffer.pop(buffer);
```

My solution added `#include "platform/CircularBuffer.h"` in Nano33BLESensorBuffer.h

Thanks

**Comment by DaleGia** [comment] 2020-09-12 17:36
Hi @sabas1080. Weird! I briefly tried to replicate this with Arduino IDE today and suffered no compilation errors, Although you are not the only one to report this issue. I will investigate this over the next couple of days and get back to you.

**Comment by sabas1080** [comment] 2020-09-12 21:45
The core that I use is

https://github.com/arduino/ArduinoCore-mbed

Thanks @DaleGia

**Comment by DaleGia** [comment] 2020-09-14 13:26
Hi again @sabas1080 

Could you possible help me out with a bit more info? What IDE are you using. What Board Package, and what version number? I cannot replicate this issue with both PlatformIO on VSCode and the Arduino IDE with the Arduino nRF218x Boards (Mbed OS) Board Package version 1.1.6.

I am happy to add the includes with needed, but I just want to try and understand the cause of the issue a bit better first.

**Comment by sabas1080** [comment] 2020-09-14 17:06
@DaleGia 
Arduino Mbed https://github.com/arduino/ArduinoCore-mbed  is not the same as Arduino nRF528x Boards https://github.com/arduino/ArduinoCore-nRF528x-mbedos

Check Arduino Mbed please

**Comment by DaleGia** [comment] 2020-09-15 13:46
I added the <CircularBuffer.h> include which seems to have solved the issue between these two cores. In a slightly related matter, There is still an unresolved issue regarding the use of the ArduinoCore-mbed core with the MicrophoneRMS implementation, so if possible I would reccomend using this ArduinoCore-nRF528x-mbedos core if possible. I'll close this issue now. Thanks for reporting it!

**Closed as completed by DaleGia** 2020-09-15 13:46 UTC
