### ISSUE TITLE
includes for Nano33BLESensorBuffer

### ISSUE THREAD

**Issue by amorsch** [DaleGia/Nano33BLESensor#3] opened 2020-09-13 07:17 UTC
To use Nano33BLESensorBuffer.h with Arduino IDE I had to include 
#include "mbed.h"
#include "platform/CircularBuffer.h"

Otherwise compilation stops with 
/Users/morsch/Documents/Arduino/libraries/Nano33BLESensor-master/src/Nano33BLESensorBuffer.h:97:11: error: 'class Nano33BLESensorBuffer<Nano33BLEMicrophoneRMSData>' has no member named 'buffer'
     this->buffer.push(data);
     ~~~~~~^~~~~~

**Comment by amorsch** [comment] 2020-09-13 08:02
sorry, duplication of #1 
but it is clear that these inlcudes are needed.

**Comment by DaleGia** [comment] 2020-09-14 13:25
Hi @amorsch,

Could you possible help me out with a bit more info? What IDE are you using. What Board Package, and what version number? I cannot replicate this issue with both PlatformIO on VSCode and the Arduino IDE with the Arduino nRF218x Boards (Mbed OS) Board Package version 1.1.6.

I am happy to add the includes with needed, but I just want to try and understand the cause of the issue a bit better first.

**Comment by DaleGia** [comment] 2020-09-15 13:47
I added the <CircularBuffer.h> include which seems to have solved the issue between these two cores. In a slightly related matter, There is still an unresolved issue regarding the use of the ArduinoCore-mbed core with the MicrophoneRMS implementation, so if possible I would recommend using this ArduinoCore-nRF528x-mbedos core if possible. I'll close this issue now. Thanks for reporting it!

**Closed as completed by DaleGia** 2020-09-15 13:47 UTC
